# Generated by Django 3.2.3 on 2021-06-17 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a16fa52-eb09-4e2c-97d6-fff5cf45992f'), primary_key=True, serialize=False),
        ),
    ]
