# Generated by Django 3.2.3 on 2021-06-17 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cdf79db8-934c-4b0e-9841-4fa186874c0b'), primary_key=True, serialize=False),
        ),
    ]
