# Generated by Django 3.2.3 on 2021-06-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%dT%H:%M:%S'),
        ),
    ]
