# Generated by Django 3.2.3 on 2021-06-21 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.SlugField(unique=True)),
                ('file', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photos',
            field=models.ManyToManyField(to='pets.Photo'),
        ),
    ]
