# Generated by Django 3.2.3 on 2021-06-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20210621_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
