# Generated by Django 3.2.3 on 2021-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_remove_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photos',
            field=models.ManyToManyField(blank=True, to='pets.Photo'),
        ),
    ]
