# Generated by Django 3.2.3 on 2021-06-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
            preserve_default=False,
        ),
    ]
